import { test, expect, type Page } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
async function json(page:Page,url:string,method='GET',body?:unknown){return page.evaluate(async({url,method,body})=>{const r=await fetch(url,{method,headers:method==='GET'?{}:{'Content-Type':'application/json','X-Workbench':'1'},body:method==='GET'?undefined:JSON.stringify(body||{})});if(!r.ok)throw new Error(await r.text());return r.json();},{url,method,body});}
test('production: 1000 files stay scoped to expanded directories; popup, reconnection and read-only lifecycle',async({page,context})=>{
 test.setTimeout(90000);const temp=await fs.mkdtemp(path.join(os.tmpdir(),'agentdeck-load-'));const roots=Array.from({length:3},(_,i)=>path.join(temp,`load-${i}`));for(const root of roots)await fs.mkdir(root);
 await Promise.all(Array.from({length:1000},(_,i)=>fs.writeFile(path.join(roots[i%3],`report-${i}.html`),`<p>${i}</p>`)));
 try{await page.goto('/');const s=await json(page,'/api/projects');for(const p of s.projects)await json(page,`/api/projects/${p.id}`,'DELETE');let treeRequests=0;page.on('request',r=>{if(r.url().includes('/tree'))treeRequests++;});
 const start=Date.now();for(const [i,root] of roots.entries())await json(page,'/api/projects','POST',{name:`目录 ${i}`,mount:{label:`目录 ${i}`,absolutePath:root}});await expect(page.getByRole('treeitem',{name:'目录 2',exact:true})).toBeVisible();expect(treeRequests).toBe(0);const registrationMs=Date.now()-start;
 const opened=Date.now();await page.getByRole('treeitem',{name:'目录 0',exact:true}).click();await expect(page.locator('.node-main:not(.folder)')).toHaveCount(334);const firstDirectoryMs=Date.now()-opened;console.log(JSON.stringify({measurement:'lazy-1000-files',registrationMs,firstDirectoryMs,mounts:3,files:1000}));
 await page.getByRole('treeitem',{name:'report-0.html',exact:true}).click();const popupPromise=page.waitForEvent('popup');await page.getByRole('link',{name:'新标签',exact:true}).click();const popup=await popupPromise;await expect(popup.locator('p')).toHaveText('0');await expect(popup.locator('iframe')).toHaveCount(0);await fs.writeFile(path.join(roots[0],'report-0.html'),'<p>updated</p>');await expect(page.getByRole('status')).toContainText('文件已更新',{timeout:10000});await expect(page.frameLocator('iframe').locator('p')).toHaveText('0');await expect(popup.locator('p')).toHaveText('0');await popup.reload();await expect(popup.locator('p')).toHaveText('updated');await page.getByRole('button',{name:'加载更新'}).click();await expect(page.frameLocator('iframe').locator('p')).toHaveText('updated');await popup.close();
 await context.setOffline(true);await fs.writeFile(path.join(roots[0],'reconnected.html'),'<p>reconnected</p>');await context.setOffline(false);await expect(page.getByRole('treeitem',{name:'reconnected.html',exact:true})).toBeVisible({timeout:12000});
 const before=await fs.readFile(path.join(roots[0],'report-0.html'),'utf8');const snapshot=await json(page,'/api/projects');const m=snapshot.mounts[0];const raw=`http://127.0.0.1:4411/m/${m.id}/report-0.html`;await json(page,`/api/mounts/${m.id}`,'PATCH',{enabled:false});expect((await page.request.get(raw)).status()).toBe(410);await json(page,`/api/mounts/${m.id}`,'PATCH',{enabled:true});expect((await page.request.get(raw)).status()).toBe(200);for(const p of snapshot.projects)await json(page,`/api/projects/${p.id}`,'DELETE');expect((await page.request.get(raw)).status()).toBe(404);expect(await fs.readFile(path.join(roots[0],'report-0.html'),'utf8')).toBe(before);
 }finally{await fs.rm(temp,{recursive:true,force:true});}
});
