import { test, expect, type Page } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';

let root: string;
export const pane = (page: Page, index: number) => page.locator(`[data-pane="${index}"]`);
test.beforeAll(async () => {
  root = await fs.mkdtemp(path.join(os.tmpdir(), 'agentdeck-reading-'));
  for (const name of ['a', 'b', 'c', 'd']) {
    await fs.writeFile(path.join(root, `${name}.html`), `<title>${name}</title><input id="draft"><div style="height:3000px">${name}</div><script>window.pageKeys=0;window.addEventListener('keydown',e=>{if(e.key==='f')window.pageKeys++;},true)</script>`);
    await fs.writeFile(path.join(root, `${name}.md`), `# ${name}\n\n${'阅读内容\n\n'.repeat(200)}`);
    await fs.writeFile(path.join(root, `${name}.txt`), `纯文本 ${name}\n`);
  }
});
test.afterAll(async () => { await fs.rm(root, { recursive: true, force: true }); });
test.beforeEach(async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/');
  await page.evaluate(async root => {
    const request = (url: string, method = 'GET', body?: unknown) => fetch(url, { method, headers: method === 'GET' ? {} : { 'Content-Type': 'application/json', 'X-Workbench': '1' }, body: method === 'GET' ? undefined : JSON.stringify(body || {}) }).then(async r => { const data = await r.json(); if (!r.ok) throw new Error(JSON.stringify(data)); return data; });
    const snapshot = await request('/api/projects');
    for (const p of snapshot.projects) await request(`/api/projects/${p.id}`, 'DELETE');
    await request('/api/projects', 'POST', { name: '阅读验证', mount: { label: '文件', absolutePath: root } });
  }, root);
  await page.getByRole('treeitem', { name: '阅读验证', exact: true }).click();
});

test('mixed panes retain same-file instances through repeated splits, mouse resize and maximize', async ({ page }) => {
  await page.getByRole('treeitem', { name: 'a.html', exact: true }).dblclick();
  const left = pane(page, 0), right = pane(page, 1);
  await left.frameLocator('iframe').locator('#draft').fill('左侧输入');
  const original = page.frames().find(f => f.url().endsWith('/a.html'))!;
  await original.evaluate(() => { (window as unknown as { identity: string }).identity = 'original'; window.scrollTo(0, 400); });
  await left.getByRole('button', { name: '分屏打开' }).click();
  await right.frameLocator('iframe').locator('#draft').fill('右侧输入');
  await expect(page.getByRole('tabpanel')).toHaveCount(2);
  await expect(page.locator('[role=tab][id]')).toHaveCount(2);
  const ids = await page.locator('[role=tab][id]').evaluateAll(elements => elements.map(el => el.id));
  expect(new Set(ids).size).toBe(2);
  await right.getByRole('tab').click();
  await page.keyboard.press('o');
  const third = pane(page, 2);
  await expect(third).toBeVisible();
  const upper = await right.boundingBox(), lower = await third.boundingBox();
  expect(lower!.y).toBeGreaterThan(upper!.y + upper!.height - 1);
  await expect(left.frameLocator('iframe').locator('#draft')).toHaveValue('左侧输入');
  await expect(right.frameLocator('iframe').locator('#draft')).toHaveValue('右侧输入');
  expect(await original.evaluate(() => (window as unknown as { identity: string }).identity)).toBe('original');
  const divider = page.getByRole('separator', { name: '调整阅读区比例' }).last();
  const handle = await divider.boundingBox();
  await page.mouse.move(handle!.x + handle!.width / 2, handle!.y + handle!.height / 2);
  await page.mouse.down(); await page.mouse.move(handle!.x + handle!.width / 2, handle!.y - 45); await page.mouse.up();
  const ratio = await divider.getAttribute('aria-valuenow');
  expect(Number(ratio)).toBeLessThan(50);
  await right.getByRole('tab').click();
  await page.keyboard.press('x');
  await expect(left).toBeHidden(); await expect(right).toBeVisible(); await expect(third).toBeHidden();
  await page.keyboard.press('x');
  await expect(left.frameLocator('iframe').locator('#draft')).toHaveValue('左侧输入');
  await expect(right.frameLocator('iframe').locator('#draft')).toHaveValue('右侧输入');
  await page.setViewportSize({ width: 900, height: 1440 });
  await expect(divider).toHaveAttribute('aria-valuenow', ratio!);
  await page.screenshot({ path: 'test-results/reading-portrait.png' });
});

test('new files replace only the selected pane temporary page', async ({ page }) => {
  await page.getByRole('treeitem', { name: 'a.md', exact: true }).click();
  await page.getByRole('button', { name: '左右分屏', exact: true }).click();
  await pane(page, 1).getByRole('button', { name: '选择文件', exact: true }).click();
  await page.getByRole('treeitem', { name: 'b.md', exact: true }).click();
  await page.getByRole('treeitem', { name: 'c.md', exact: true }).click();
  await expect(pane(page, 0).getByRole('tab')).toHaveText('a.md');
  await expect(pane(page, 1).getByRole('tab')).toHaveText('c.md');
  await expect(pane(page, 0).locator('.markdown h1')).toHaveText('a');
  await pane(page, 0).getByRole('tab').click();
  await page.getByRole('treeitem', { name: 'd.md', exact: true }).dblclick();
  await expect(pane(page, 1).locator('.markdown h1')).toHaveText('c');
  await expect(pane(page, 0).locator('.page-tab.temporary')).toHaveCount(0);
});

test('W closes only once per press and last-tab policy keeps or removes the empty region', async ({ page }) => {
  await page.getByRole('treeitem', { name: 'a.md', exact: true }).dblclick();
  await page.getByRole('treeitem', { name: 'b.md', exact: true }).dblclick();
  await expect(pane(page, 0).getByRole('tab')).toHaveCount(2);
  await page.keyboard.down('w');
  await expect(pane(page, 0).getByRole('tab')).toHaveCount(1);
  await page.keyboard.down('w');
  await expect(pane(page, 0).getByRole('tab')).toHaveCount(1);
  await page.keyboard.up('w');
  await page.keyboard.press('e');
  await expect(pane(page, 1)).toBeVisible();
  await page.getByRole('treeitem', { name: 'c.md', exact: true }).click();
  await page.keyboard.press('w');
  await expect(pane(page, 1)).toBeVisible();
  await expect(pane(page, 1).getByRole('tab')).toHaveCount(0);
  await page.keyboard.press('w');
  await expect(page.locator('[data-pane]')).toHaveCount(2);
  await page.getByRole('button', { name: '设置', exact: true }).click();
  const settings = page.getByRole('dialog', { name: '设置', exact: true });
  await settings.getByRole('button', { name: '阅读布局', exact: true }).click();
  await settings.getByLabel('关闭阅读区最后一个标签后').selectOption('remove');
  await settings.getByRole('button', { name: '关闭设置' }).click();
  await page.getByRole('treeitem', { name: 'c.md', exact: true }).click();
  await page.keyboard.press('w');
  await expect(pane(page, 1)).toHaveCount(0);
  await expect(pane(page, 0).getByRole('tab')).toHaveCount(1);
  await page.keyboard.press('w');
  await expect(pane(page, 0)).toBeVisible();
  await expect(pane(page, 0).getByRole('tab')).toHaveCount(0);
});

test('fixed current tabs open history in a new tab without replacing a background temporary file', async ({ page }) => {
  const first = pane(page, 0);
  await page.getByRole('treeitem', { name: 'a.md', exact: true }).dblclick();
  await page.getByRole('treeitem', { name: 'b.md', exact: true }).click();
  await first.getByRole('tab', { name: 'a.md', exact: true }).click();
  await page.getByRole('treeitem', { name: 'c.md', exact: true }).click();
  await expect(first.getByRole('tab')).toHaveText(['a.md', 'b.md', 'c.md']);
  await first.getByRole('tab', { name: 'c.md', exact: true }).dblclick();
  await page.keyboard.press('Alt+ArrowLeft');
  await expect(first.getByRole('tab', { name: 'a.md', exact: true })).toHaveAttribute('aria-selected', 'true');
  await page.keyboard.press('Alt+ArrowLeft');
  await expect(first.getByRole('tab', { name: 'b.md', exact: true })).toHaveAttribute('aria-selected', 'true');
  await page.getByRole('treeitem', { name: 'd.md', exact: true }).dblclick();
  await page.keyboard.press('Alt+ArrowLeft');
  await expect(first.getByRole('tab')).toHaveCount(4);
  await expect(first.getByRole('tab', { name: 'c.md', exact: true })).toBeVisible();
  await expect(first.getByRole('tab', { name: 'd.md', exact: true })).toBeVisible();
  await expect(first.getByRole('tab', { name: 'b.md', exact: true })).toHaveAttribute('aria-selected', 'true');
});

test('Alt history restores replaced text previews, isolates panes and truncates forward visits', async ({ page }) => {
  const first = pane(page, 0), second = pane(page, 1);
  await page.getByRole('treeitem', { name: 'a.md', exact: true }).click();
  await expect(first.locator('.markdown h1')).toHaveText('a');
  await first.locator('.reader').evaluate(el => { el.scrollTop = 450; });
  await page.getByRole('treeitem', { name: 'b.md', exact: true }).click();
  await page.getByRole('treeitem', { name: 'c.md', exact: true }).click();
  await page.keyboard.press('Alt+ArrowLeft');
  await expect(first.locator('.markdown h1')).toHaveText('b');
  await page.keyboard.press('Alt+ArrowLeft');
  await expect(first.locator('.markdown h1')).toHaveText('a');
  await expect.poll(()=>first.locator('.reader').evaluate(el=>el.scrollTop)).toBe(450);
  await page.keyboard.press('Alt+ArrowLeft');
  await expect(first.locator('.markdown h1')).toHaveText('a');
  await expect(page).toHaveURL(/127\.0\.0\.1:4410/);
  await page.keyboard.press('Alt+ArrowRight');
  await expect(first.locator('.markdown h1')).toHaveText('b');
  await page.getByRole('treeitem', { name: 'd.md', exact: true }).click();
  await expect(first.getByRole('button', { name: '前进', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: '上下分屏', exact: true }).click();
  await second.getByRole('button', { name: '选择文件', exact: true }).click();
  await page.getByRole('treeitem', { name: 'a.md', exact: true }).click();
  await page.getByRole('treeitem', { name: 'c.md', exact: true }).click();
  await page.keyboard.press('Alt+ArrowLeft');
  await expect(second.locator('.markdown h1')).toHaveText('a');
  await expect(first.locator('.markdown h1')).toHaveText('d');
});

test('HTML focus routes shortcuts to its own pane, protects typing and supports file overrides', async ({ page }) => {
  await page.getByRole('button', { name: '设置', exact: true }).click();
  const settings = page.getByRole('dialog', { name: '设置', exact: true });
  await settings.getByRole('button', { name: '快捷键', exact: true }).click();
  await settings.getByLabel('HTML 内快捷键处理').selectOption('workbench');
  await settings.getByRole('button', { name: '关闭设置' }).click();
  await page.getByRole('treeitem', { name: 'a.html', exact: true }).dblclick();
  const first = pane(page, 0), second = pane(page, 1);
  await expect(first.locator('.bridge-state')).toHaveText('工作台快捷键优先');
  const frameA = page.frames().find(f => f.url().endsWith('/a.html'))!;
  await first.frameLocator('iframe').locator('body').click({position:{x:60,y:150}});
  await page.keyboard.press('f');
  await expect(page.locator('.shell')).toHaveClass(/immersive/);
  expect(await frameA.evaluate(()=>(window as unknown as {pageKeys:number}).pageKeys)).toBe(0);
  await first.frameLocator('iframe').locator('#draft').fill('输入');
  await page.keyboard.type('fb/?oexw');
  await expect(first.frameLocator('iframe').locator('#draft')).toHaveValue('输入fb/?oexw');
  await page.keyboard.press('Escape');
  await expect(page.locator('.shell')).not.toHaveClass(/immersive/);
  await first.frameLocator('iframe').locator('body').click({position:{x:60,y:150}});
  await page.keyboard.press('e');
  await second.getByRole('button', { name: '选择文件', exact: true }).click();
  await page.getByRole('treeitem', { name: 'b.html', exact: true }).click();
  await page.getByRole('treeitem', { name: 'c.html', exact: true }).click();
  await expect(second.locator('.bridge-state')).toHaveText('工作台快捷键优先');
  await first.frameLocator('iframe').locator('body').click({position:{x:60,y:150}});
  await second.frameLocator('iframe').locator('body').click({position:{x:60,y:150}});
  await page.keyboard.press('Alt+ArrowLeft');
  await expect(second.getByRole('tab')).toHaveText('b.html');
  await expect(first.getByRole('tab')).toHaveText('a.html');
  await second.getByRole('button', { name: '更多设置' }).click();
  await page.getByLabel('此 HTML 快捷键').selectOption('web');
  await page.keyboard.press('Escape');
  await expect(second.locator('.bridge-state')).toHaveText('网页快捷键优先');
  await second.frameLocator('iframe').locator('body').click({position:{x:60,y:150}});
  await page.keyboard.press('f');
  await expect(page.locator('.shell')).not.toHaveClass(/immersive/);
  const frameB = page.frames().find(f=>f.url().endsWith('/b.html'))!;
  expect(await frameB.evaluate(()=>(window as unknown as {pageKeys:number}).pageKeys)).toBe(1);
  await page.keyboard.type('oexw');
  await expect(page.locator('[data-pane]')).toHaveCount(2);
  await expect(second.getByRole('tab')).toHaveText('b.html');
});

test('HTML history restores document scroll and failed bridge exposes unavailable status', async ({ page }) => {
  await page.getByRole('treeitem', { name: 'a.html', exact: true }).click();
  const first = pane(page, 0);
  await expect(first.locator('.bridge-state')).toHaveAttribute('data-bridge-status','ready');
  const frame = page.frames().find(f=>f.url().endsWith('/a.html'))!;
  await frame.evaluate(()=>window.scrollTo(0,500));
  // Give the scroll bridge a rendering frame to report the reading position.
  await frame.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));
  await page.getByRole('treeitem', { name: 'b.html', exact: true }).click();
  await first.getByRole('button', { name: '后退', exact: true }).click();
  await expect.poll(async()=>page.frames().find(f=>f.url().endsWith('/a.html'))?.evaluate(()=>window.scrollY)).toBe(500);
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await page.getByRole('dialog', { name: '设置', exact: true }).getByRole('button', { name: '快捷键', exact: true }).click();
  await page.getByLabel('HTML 内快捷键处理').selectOption('workbench');
  await page.getByRole('button', { name: '关闭设置' }).click();
  await page.route('**/__agentdeck/bridge.js',route=>route.abort());
  await first.getByRole('button', { name: '刷新', exact: true }).click();
  await expect(first.locator('.bridge-state')).toContainText('当前页面未接管快捷键');
});

test('more settings floats without resizing, closes outside and on Escape', async ({ page }) => {
  await page.getByRole('treeitem', { name: 'a.md', exact: true }).click();
  await page.getByRole('button', { name: '左右分屏', exact: true }).click();
  const first = pane(page, 0), second = pane(page, 1);
  await second.getByRole('button', { name: '选择文件', exact: true }).click();
  await page.getByRole('treeitem', { name: 'b.md', exact: true }).click();
  const before=await first.locator('.reader').boundingBox();
  await first.getByRole('button', { name: '更多设置' }).click();
  await expect(page.locator('[data-viewer-settings]')).toBeVisible();
  expect((await first.locator('.reader').boundingBox())!.height).toBe(before!.height);
  await second.getByRole('button', { name: '更多设置' }).click();
  await expect(page.locator('[data-viewer-settings]')).toHaveCount(1);
  await page.getByRole('button', { name: '更多设置' }).last().focus();
  await page.keyboard.press('Escape');
  await expect(page.locator('[data-viewer-settings]')).toHaveCount(0);
  await first.getByRole('button', { name: '更多设置' }).click();
  await first.locator('.reader').click();
  await expect(page.locator('[data-viewer-settings]')).toHaveCount(0);
});

test('direct source and copy actions leave HTML input intact and close its popover', async ({page,context})=>{
  await context.grantPermissions(['clipboard-read','clipboard-write']);
  await page.getByRole('treeitem',{name:'a.html',exact:true}).dblclick();
  const first=pane(page,0);
  await first.frameLocator('iframe').locator('#draft').fill('未保存的输入');
  await first.getByRole('button',{name:'更多设置'}).click();
  await first.getByRole('button',{name:'查看源码'}).click();
  await expect(page.locator('[data-viewer-settings]')).toHaveCount(0);
  await expect(first.locator('.reader pre')).toContainText('<input id="draft">');
  await first.getByRole('button',{name:'返回阅读'}).click();
  await expect(first.frameLocator('iframe').locator('#draft')).toHaveValue('未保存的输入');
  await first.getByRole('button',{name:'复制原文'}).click();
  expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('<input id="draft">');
  await expect(first.locator('.notice')).toHaveCount(0);
  await first.getByRole('button',{name:'更多设置'}).click();
  await first.frameLocator('iframe').locator('body').click({position:{x:60,y:150}});
  await expect(page.locator('[data-viewer-settings]')).toHaveCount(0);
});

test('seven icon actions fit one row and overflow from right to left as pane narrows',async({page,context})=>{
  await context.grantPermissions(['clipboard-read','clipboard-write']);
  await page.getByRole('treeitem',{name:'a.html',exact:true}).dblclick();
  const first=pane(page,0),toolbar=first.locator('.toolbar');
  const order=['refresh','favorite','external','split','source','copy'];
  const actionIds=()=>toolbar.locator('[data-toolbar-action]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-toolbar-action')));
  await expect.poll(actionIds).toEqual(order);
  await expect(first.locator('.quick-actions')).toHaveCount(0);
  const hints=await toolbar.locator('.icon-button').evaluateAll(elements=>elements.map(element=>({label:element.getAttribute('aria-label'),hint:element.getAttribute('data-tooltip'),text:element.textContent?.trim()})));
  expect(hints).toHaveLength(7);
  for(const hint of hints){expect(hint.label).toBeTruthy();expect(hint.hint).toBeTruthy();expect(hint.text).toBe('');}
  await toolbar.getByRole('button',{name:'刷新',exact:true}).hover();
  expect(await toolbar.getByRole('button',{name:'刷新',exact:true}).evaluate(element=>getComputedStyle(element,'::after').visibility)).toBe('visible');
  await page.screenshot({path:'test-results/toolbar-wide.png'});
  const draft=first.frameLocator('iframe').locator('#draft');await draft.fill('缩放后保留');
  const frame=page.frames().find(item=>item.url().endsWith('/a.html'))!;
  await frame.evaluate(()=>{(window as unknown as {instance:string}).instance='same';});
  await page.getByRole('button',{name:'左右分屏',exact:true}).click();
  await page.getByRole('separator',{name:'调整侧栏宽度'}).focus();await page.keyboard.press('End');
  await page.setViewportSize({width:760,height:1000});
  await expect.poll(async()=>(await actionIds()).length).toBeLessThan(5);
  const visible=await actionIds();
  expect(visible).toEqual(order.slice(0,visible.length));
  await expect(toolbar.getByRole('button',{name:'更多设置'})).toBeVisible();
  await toolbar.getByRole('button',{name:'更多设置'}).click();
  await page.screenshot({path:'test-results/toolbar-narrow.png'});
  const overflow=page.getByRole('group',{name:'收起的工具栏操作'});
  expect(await overflow.locator('[data-overflow-action]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-overflow-action')))).toEqual(order.slice(visible.length));
  await overflow.getByRole('button',{name:'查看源码'}).click();
  await expect(first.locator('.reader pre')).toContainText('<input id="draft">');
  await toolbar.getByRole('button',{name:'更多设置'}).click();
  await overflow.getByRole('button',{name:'返回阅读'}).click();
  await expect(draft).toHaveValue('缩放后保留');
  expect(await frame.evaluate(()=>(window as unknown as {instance:string}).instance)).toBe('same');
  await toolbar.getByRole('button',{name:'更多设置'}).click();
  await overflow.getByRole('button',{name:'复制原文'}).click();
  expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('<input id="draft">');
  await page.setViewportSize({width:1440,height:1000});
  await expect.poll(actionIds).toEqual(order);
});

test('document font size persists for Markdown and text while HTML keeps its own size',async({page})=>{
  await page.getByRole('treeitem',{name:'a.md',exact:true}).click();
  const first=pane(page,0);
  await expect(first.locator('.reader')).toHaveCSS('font-size','14px');
  await page.getByRole('button',{name:'设置',exact:true}).click();
  const settings=page.getByRole('dialog',{name:'设置',exact:true});
  await settings.getByRole('button',{name:'阅读布局'}).click();
  const slider=settings.getByRole('slider',{name:'文档字号'});
  await slider.focus();await page.keyboard.press('End');
  await expect(slider).toHaveValue('24');
  await expect(first.locator('.reader')).toHaveCSS('font-size','24px');
  await settings.getByRole('button',{name:'关闭设置'}).click();
  await page.reload();
  await expect(first.locator('.reader')).toHaveCSS('font-size','24px');
  if (!await page.getByRole('treeitem',{name:'a.txt',exact:true}).isVisible()) await page.getByRole('treeitem',{name:'阅读验证',exact:true}).click();
  await page.getByRole('treeitem',{name:'a.txt',exact:true}).click();
  await expect(first.locator('.viewer:not([hidden]) .reader')).toHaveCSS('font-size','24px');
  await expect(first.locator('.viewer:not([hidden]) pre')).toHaveCSS('font-size','24px');
  await page.getByRole('treeitem',{name:'a.html',exact:true}).click();
  await expect(first.frameLocator('iframe').locator('body')).toHaveCSS('font-size','16px');
  await first.getByRole('button',{name:'查看源码'}).click();
  await expect(first.locator('.viewer:not([hidden]) .reader')).toHaveCSS('font-size','13px');
});

test('Alt navigation wins over splitter and folder arrow handling', async ({ page }) => {
  await page.getByRole('treeitem', { name: 'a.md', exact: true }).click();
  await page.getByRole('treeitem', { name: 'b.md', exact: true }).click();
  await page.getByRole('button', { name: '左右分屏', exact: true }).click();
  await pane(page, 0).getByRole('tab').click();
  const sidebar = page.getByRole('separator', { name: '调整侧栏宽度' });
  const split = page.getByRole('separator', { name: '调整阅读区比例' });
  const sidebarWidth = await sidebar.getAttribute('aria-valuenow');
  const ratio = await split.getAttribute('aria-valuenow');
  await sidebar.focus(); await page.keyboard.press('Alt+ArrowLeft');
  await expect(pane(page, 0).locator('.markdown h1')).toHaveText('a');
  await expect(sidebar).toHaveAttribute('aria-valuenow', sidebarWidth!);
  await split.click(); await page.keyboard.press('Alt+ArrowRight');
  await expect(pane(page, 0).locator('.markdown h1')).toHaveText('b');
  await expect(split).toHaveAttribute('aria-valuenow', ratio!);
  const folder = page.getByRole('treeitem', { name: '阅读验证', exact: true });
  await folder.focus(); await page.keyboard.press('Alt+ArrowLeft');
  await expect(pane(page, 0).locator('.markdown h1')).toHaveText('a');
  await expect(folder).toHaveAttribute('aria-expanded', 'true');
});
