import { test, expect, type Page } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
let temp:string;let otherDisk:string;
async function json(page:Page,url:string,method='GET',body?:unknown){return page.evaluate(async({url,method,body})=>{const r=await fetch(url,{method,headers:method==='GET'?{}:{'Content-Type':'application/json','X-Workbench':'1'},body:method==='GET'?undefined:JSON.stringify(body||{})});return {status:r.status,data:await r.json()};},{url,method,body});}
async function add(page:Page,name:string,dir:string,mode='content',tools=''){
  await page.locator('.explorer-header').getByRole('button',{name:'添加项目',exact:true}).click();
  await page.getByLabel('项目名称',{exact:true}).fill(name);await page.getByLabel('真实绝对路径').fill(dir);
  await page.getByRole('button',{name:'确认范围并保存'}).click();await expect(page.locator('.overlay')).toHaveCount(0);
}
test.beforeAll(async()=>{temp=await fs.mkdtemp(path.join(os.tmpdir(),'agentdeck-browser-'));otherDisk=await fs.mkdtemp(path.join(process.cwd(),'test-fixtures-'));await fs.cp(path.resolve('examples'),temp,{recursive:true});await fs.cp(path.resolve('examples/company/tool/dist'),path.join(otherDisk,'built'),{recursive:true});});
test.afterAll(async()=>{await fs.rm(temp,{recursive:true,force:true});await fs.rm(otherDisk,{recursive:true,force:true});});
test('production: mount projects, run native and built tools, render relative assets',async({page})=>{
 await page.goto('/');const snapshot=await json(page,'/api/projects');for(const p of snapshot.data.projects)await json(page,`/api/projects/${p.id}`,'DELETE');await page.reload();
 await add(page,'大宗商品',path.join(temp,'commodities'));await add(page,'AI 行业',path.join(temp,'ai'));await add(page,'公司研究',path.join(otherDisk,'built'));
 await page.getByRole('treeitem',{name:'AI 行业',exact:true}).click();await page.getByRole('treeitem',{name:'工具',exact:true}).click();await page.getByRole('treeitem',{name:'cleaner',exact:true}).click();await page.getByRole('treeitem',{name:'index.html',exact:true}).click();let frame=page.frameLocator('iframe');await frame.locator('#input').fill('  hello    world  ');await frame.getByRole('button',{name:'整理空白'}).click();await expect(frame.locator('#output')).toHaveText('hello world');
 await page.getByRole('treeitem',{name:'公司研究',exact:true}).click();await page.locator('.project-group').filter({hasText:'公司研究'}).getByRole('treeitem',{name:'index.html',exact:true}).click();frame=page.frameLocator('iframe');await frame.locator('#tonnes').fill('3.4');await frame.getByRole('button',{name:'换算',exact:true}).click();await expect(frame.locator('#result')).toHaveText('3400 千克');
 await page.getByRole('treeitem',{name:'大宗商品',exact:true}).click();await page.getByRole('treeitem',{name:'copper',exact:true}).click();await page.locator('.project-group').filter({hasText:'大宗商品'}).getByRole('treeitem',{name:'index.html',exact:true}).click();frame=page.frameLocator('iframe');await expect(frame.locator('#data')).toContainText('CSV 已读取');await expect(frame.locator('img')).toBeVisible();
 await page.setViewportSize({width:1440,height:900});await page.screenshot({path:'test-results/workbench.png'});await page.setViewportSize({width:1080,height:1920});await page.screenshot({path:'test-results/workbench-portrait.png'});await page.getByRole('button',{name:'沉浸',exact:true}).click();await page.screenshot({path:'test-results/workbench-immersive.png'});
});
test('production: append, overlap, rename and remove registration without changing files',async({page})=>{
 await page.goto('/');const snapshot=await json(page,'/api/projects');for(const p of snapshot.data.projects)await json(page,`/api/projects/${p.id}`,'DELETE');await page.reload();
 const primary=path.join(temp,'manage-primary'),extra=path.join(temp,'manage-extra');await fs.mkdir(path.join(primary,'child'),{recursive:true});await fs.mkdir(extra,{recursive:true});await fs.writeFile(path.join(primary,'one.txt'),'原文件');await fs.writeFile(path.join(extra,'two.txt'),'第二个文件');
 await add(page,'多目录项目',primary);await page.getByRole('button',{name:'管理项目：多目录项目'}).click();await page.getByLabel('目录别名',{exact:true}).fill('附加目录');await page.getByLabel('真实绝对路径').fill(extra);await page.getByRole('button',{name:'确认范围并保存'}).click();await expect(page.locator('.overlay')).toHaveCount(0);
 await page.getByRole('treeitem',{name:'附加目录',exact:true}).click();await page.getByRole('treeitem',{name:'two.txt',exact:true}).click();await expect(page.locator('.reader pre')).toHaveText('第二个文件');
 await page.getByRole('button',{name:'管理项目：多目录项目'}).click();await page.getByLabel('真实绝对路径').fill(path.join(primary,'child'));await page.getByRole('button',{name:'确认范围并保存'}).click();await expect(page.locator('.dialog [role=alert]')).toContainText('已包含');
 await page.getByLabel('项目名称',{exact:true}).fill('改名项目');await page.getByRole('button',{name:'保存名称'}).click();page.once('dialog',d=>void d.dismiss());await page.getByRole('button',{name:'移除项目',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();page.once('dialog',d=>void d.accept());await page.getByRole('button',{name:'移除项目',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('treeitem',{name:'附加目录',exact:true})).toHaveCount(0);expect(await fs.readFile(path.join(primary,'one.txt'),'utf8')).toBe('原文件');
});
test('production: changed files prompt without replacing input; directory updates and recovery are local',async({page})=>{
 await page.goto('/');const snapshot=await json(page,'/api/projects');for(const p of snapshot.data.projects)await json(page,`/api/projects/${p.id}`,'DELETE');
 const root=path.join(temp,'changing');await fs.mkdir(root);await fs.writeFile(path.join(root,'tool.html'),'<input id="draft">');await add(page,'更新验证',root);await page.getByRole('treeitem',{name:'更新验证',exact:true}).click();await page.getByRole('treeitem',{name:'tool.html',exact:true}).click();await page.frameLocator('iframe').locator('#draft').fill('保留输入');
 await fs.writeFile(path.join(root,'tool.html'),'<input id="draft"><p>新版本</p>');await expect(page.getByRole('status')).toContainText('文件已更新',{timeout:10000});await expect(page.frameLocator('iframe').locator('#draft')).toHaveValue('保留输入');
 await fs.writeFile(path.join(root,'new.md'),'# 新笔记');await expect(page.getByRole('treeitem',{name:'new.md',exact:true})).toBeVisible({timeout:10000});await expect(page.frameLocator('iframe').locator('#draft')).toHaveValue('保留输入');await page.getByRole('button',{name:'加载更新'}).click();await expect(page.frameLocator('iframe').locator('p')).toHaveText('新版本');
 await fs.rename(root,root+'-offline');await expect(page.locator('.tree-message[role=alert]')).toBeVisible({timeout:10000});await fs.rename(root+'-offline',root);await page.getByRole('button',{name:'刷新目录',exact:true}).click();await expect(page.locator('.tree-message[role=alert]')).toHaveCount(0);await page.getByRole('treeitem',{name:'new.md',exact:true}).click();await expect(page.locator('.markdown h1')).toHaveText('新笔记');
});
test('production: real browser isolation, hostile Markdown, text limits, picker and cross-drive',async({page,context})=>{
  await context.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
  await page.goto('/');const snap=await json(page,'/api/projects');for(const p of snap.data.projects)await json(page,`/api/projects/${p.id}`,'DELETE');
  const root=path.join(otherDisk,'cross-drive');await fs.mkdir(root,{recursive:true});
  if(process.platform==='win32')await fs.copyFile(path.join(process.env.SystemRoot||'C:\\Windows','Fonts','arial.ttf'),path.join(root,'font.ttf'));
  await fs.writeFile(path.join(root,'probe.html'),`<title>隔离验证</title><style>@font-face{font-family:Fixture;src:url('./font.ttf')}body{font-family:Fixture,serif}</style><output id="result">running</output><script>Promise.all(['/api/projects','/api/fs/locations','/api/events'].map(p=>fetch('http://127.0.0.1:4410'+p).then(()=> 'unexpected').catch(()=> 'blocked'))).then(v=>document.querySelector('#result').textContent=v.join(','));try{top.location.href='http://127.0.0.1:4410/?hijacked=1'}catch(e){document.body.dataset.top='blocked'}</script>`);
  await fs.writeFile(path.join(root,'bad.md'),'# 安全笔记\n\n<script>window.pwned=1</script>\n\n[危险](javascript:alert(1))\n\n[越界](../../outside.txt)\n\n[正常子页](./second.md)\n\n![本地图片](./image.svg)\n');
  await fs.writeFile(path.join(root,'second.md'),'# 子页');await fs.writeFile(path.join(root,'image.svg'),'<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"><rect width="20" height="20" fill="red"/></svg>');await fs.writeFile(path.join(root,'large.md'),'a'.repeat(10*1024*1024+1));
  await page.locator('.explorer-header').getByRole('button',{name:'添加项目',exact:true}).click();await page.getByLabel('项目名称',{exact:true}).fill('跨盘验证');await page.getByRole('button',{name:'选择本机文件夹'}).click();await page.getByLabel('当前位置',{exact:true}).fill(root);await page.getByRole('button',{name:'前往',exact:true}).click();await expect(page.getByLabel('当前位置',{exact:true})).toHaveValue(root);await page.getByRole('button',{name:'选择此目录'}).click();await page.getByRole('button',{name:'确认范围并保存'}).click();await expect(page.locator('.overlay')).toHaveCount(0);
  const statuses:number[]=[];page.on('requestfailed',r=>{if(['/api/projects','/api/fs/locations','/api/events'].some(p=>r.url().endsWith(p)))statuses.push(1);});
  await page.getByRole('treeitem',{name:'跨盘验证',exact:true}).click();await page.getByRole('treeitem',{name:'probe.html',exact:true}).click();await expect(page.frameLocator('iframe').locator('#result')).toHaveText('blocked,blocked,blocked');await expect.poll(()=>statuses.length).toBe(3);expect(page.url()).not.toContain('hijacked');await expect(page.frameLocator('iframe').locator('body')).toHaveAttribute('data-top','blocked');
  if(process.platform==='win32')expect(await page.frames().find(f=>f.url().includes('/m/')&&f.url().includes('probe.html'))!.evaluate(async()=> (await document.fonts.load('16px Fixture')).length)).toBe(1);
  await page.getByRole('treeitem',{name:'bad.md',exact:true}).click();await expect(page.locator('.markdown h1')).toHaveText('安全笔记');expect(await page.evaluate(()=>('pwned' in window))).toBe(false);await expect(page.getByText('危险',{exact:true})).not.toHaveAttribute('href',/javascript/);await expect(page.getByText('越界',{exact:true})).not.toHaveAttribute('href',/outside/);await expect.poll(()=>page.locator('.markdown img').evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBe(20);await page.getByRole('link',{name:'正常子页'}).click();await expect(page.locator('.markdown h1')).toHaveText('子页');
  await page.getByRole('treeitem',{name:'large.md',exact:true}).click();await expect(page.locator('.viewer .empty')).toContainText('10 MiB');await expect(page.getByRole('link',{name:'下载原文件',exact:true})).toBeVisible();
  const cMount=await json(page,'/api/projects','POST',{name:'C 盘项目',mount:{label:'C 盘',absolutePath:path.join(temp,'ai'),toolDirectories:['工具']}});expect(cMount.status).toBe(200);
  const current=(await json(page,'/api/projects')).data;const crossDrive=path.parse(temp).root!==path.parse(otherDisk).root;if(crossDrive)expect(new Set(current.mounts.map((m:{absolutePath:string})=>path.parse(m.absolutePath).root)).size).toBe(2);else test.info().annotations.push({type:'untested',description:'本机未提供两个可写盘符，跨盘部分未执行'});
  await page.getByRole('treeitem',{name:'C 盘项目',exact:true}).click();await page.getByRole('treeitem',{name:'工具',exact:true}).click();await page.getByRole('treeitem',{name:'cleaner',exact:true}).click();await page.getByRole('treeitem',{name:'index.html',exact:true}).click();await page.frameLocator('iframe').locator('#input').fill('离线资源验证');await page.frameLocator('iframe').getByRole('button',{name:'整理空白'}).click();await expect(page.frameLocator('iframe').locator('#output')).toHaveText('离线资源验证');
});
