import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { createWorkbench, type Workbench } from '../app/server/server.js';
let temp:string,root:string,app:Workbench;
const headers={host:'127.0.0.1:4310','sec-fetch-site':'same-origin',origin:'http://127.0.0.1:4310','x-workbench':'1','content-type':'application/json'};
beforeEach(async()=>{temp=await fs.mkdtemp(path.join(os.tmpdir(),'agentdeck-lazy-'));root=path.join(temp,'project');await fs.mkdir(path.join(root,'child','grandchild'),{recursive:true});await fs.writeFile(path.join(root,'child','template.html'),'<title>{{Template}}</title>');app=await createWorkbench({stateDir:path.join(temp,'state'),port:4310,previewPort:4311});});
afterEach(async()=>{vi.restoreAllMocks();await app.close();await fs.rm(temp,{recursive:true,force:true});});
test('mount, rename, restart and file changes never recursively enumerate directories',async()=>{
 const readdir=vi.spyOn(fs,'readdir');const readFile=vi.spyOn(fs,'readFile');
 const response=await app.main.inject({method:'POST',url:'/api/projects',headers,payload:{name:'project',mount:{label:'root',absolutePath:root}}});expect(response.statusCode).toBe(200);
 const id=app.registry.data.mounts[0].id;
 await app.main.inject({method:'PATCH',url:`/api/projects/${response.json().id}`,headers,payload:{name:'renamed'}});
 await fs.writeFile(path.join(root,'new.html'),'<h1>new</h1>');
 await app.close();app=await createWorkbench({stateDir:path.join(temp,'state'),port:4310,previewPort:4311});
 expect(readdir).not.toHaveBeenCalled();expect(readFile.mock.calls.some(([p])=>String(p).endsWith('template.html'))).toBe(false);
 const result=await app.main.inject({url:`/api/mounts/${id}/tree`,headers});expect(result.statusCode).toBe(200);expect(readdir).toHaveBeenCalledTimes(1);
 expect(result.json().map((x:{name:string})=>x.name)).toEqual(['child','new.html']);
 expect((await app.main.inject({url:'/api/entries',headers})).statusCode).toBe(404);
 expect((await app.main.inject({method:'POST',url:`/api/mounts/${id}/rescan`,headers,payload:{}})).statusCode).toBe(404);
});
test('relocation and removal immediately affect directory reads without stale cached entries',async()=>{
 await app.main.inject({method:'POST',url:'/api/projects',headers,payload:{name:'project',mount:{label:'root',absolutePath:root}}});const id=app.registry.data.mounts[0].id;
 const newRoot=path.join(temp,'new');await fs.mkdir(newRoot);await fs.writeFile(path.join(newRoot,'only.txt'),'text');
 await app.main.inject({method:'PATCH',url:`/api/mounts/${id}`,headers,payload:{absolutePath:newRoot}});
 expect((await app.main.inject({url:`/api/mounts/${id}/tree`,headers})).json().map((x:{name:string})=>x.name)).toEqual(['only.txt']);
 await app.main.inject({method:'DELETE',url:`/api/mounts/${id}`,headers,payload:{}});
 expect((await app.main.inject({url:`/api/mounts/${id}/tree`,headers})).statusCode).toBe(404);
});
