import { useEffect, useState } from 'react';
import type { Entry, Snapshot } from '../shared/model.js';
import { api } from './api.js';
import { Management } from './Management.js';
import { Tree } from './Tree.js';
import './style.css';
export function App() {
  const [data,setData] = useState<Snapshot>({projects:[],mounts:[],revision:0}); const [project,setProject] = useState(''); const [manage,setManage] = useState(false); const [error,setError] = useState('');
  const [entries,setEntries]=useState<Entry[]>([]);const [current,setCurrent]=useState<Entry>();const [text,setText]=useState('');
  function reload(){ void Promise.all([api<Snapshot>('/api/projects'),api<Entry[]>('/api/entries')]).then(([s,e])=>{setData(s);setEntries(e);}).catch(e=>setError(e.message)); }
  useEffect(reload,[]);
  async function open(entry:Entry){setError('');try{const e=await api<Entry>(`/api/entries/${entry.id}`);setCurrent(e);if(!/^html?$/.test(e.format)&&e.status==='ready'){const f=await api<{text:string}>(`/api/mounts/${e.mountId}/file?path=${encodeURIComponent(e.relativePath)}`);setText(f.text);}}catch(e){setError((e as Error).message);}}
  return <div className="shell"><aside><h1>AgentDeck</h1><p>本地项目工作台</p><button onClick={()=>{setProject('');setManage(true);}}>＋ 添加项目</button><button onClick={()=>setProject('')}>全部内容</button>{data.projects.map(p=><button className={p.id===project?'active':''} key={p.id} onClick={()=>setProject(p.id)}>{p.name}</button>)}{project&&<button onClick={()=>setManage(true)}>管理挂载</button>}</aside>
  <section className="catalog"><h2>{data.projects.find(p=>p.id===project)?.name||'全部内容'}</h2><button onClick={reload}>刷新列表</button>{entries.filter(e=>!project||e.projectId===project).map(e=><button className="entry" key={e.id} onClick={()=>void open(e)}><strong>{e.kind==='tool'?'▧':'▤'} {e.title}</strong><small>{data.projects.find(p=>p.id===e.projectId)?.name} / {data.mounts.find(m=>m.id===e.mountId)?.label}</small><small>{e.relativePath||e.toolRoot} · {e.status}</small></button>)}{data.mounts.filter(m=>!project||m.projectId===project).map(m=><details key={m.id}><summary>{m.label} · {m.status}</summary><Tree mount={m} open={p=>{const e=entries.find(e=>e.mountId===m.id&&e.relativePath===p);if(e)void open(e);else window.open(`/api/mounts/${m.id}/download?path=${encodeURIComponent(p)}`,'_blank','noopener');}} /></details>)}</section>
  <section className="viewer">{error&&<p role="alert">{error}</p>}{!current?<div className="empty"><h2>{data.projects.length?'选择报告或工具':'从一个真实目录开始'}</h2><p>原地挂载，不移动原文件。HTML 保持自己的排版和资源关系。</p></div>:<><header className="toolbar"><strong>{current.title}</strong><small>{current.relativePath}</small><button onClick={()=>void open(current)}>刷新</button>{current.previewUrl&&<a href={current.previewUrl} target="_blank" rel="noreferrer">原始页面</a>}</header>{current.status!=='ready'?<div className="empty"><h2>{current.status==='pending-build'?'工具待构建 / 请选择入口':'多个候选入口待选择'}</h2><p>工作台不会执行构建命令。</p><button onClick={()=>{const entry=prompt('相对工具根的 HTML 入口',current.candidates?.[0]?.slice((current.toolRoot?.length||0)+1)||'index.html');if(entry)void api(`/api/mounts/${current.mountId}/tool-override`,'PUT',{toolRoot:current.toolRoot||'',entry}).then(()=>{reload();void open(current);}).catch(e=>setError(e.message));}}>选择 HTML 入口</button></div>: /^html?$/.test(current.format)?<iframe key={current.previewUrl} title={current.title} src={current.previewUrl} sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox allow-downloads" />:<pre>{text}</pre>}</> }</section>{manage&&<Management snapshot={data} project={data.projects.find(p=>p.id===project)} close={()=>setManage(false)} saved={reload}/>}</div>;
}
