import { useEffect, useRef, useState } from 'react';
import type { Entry, Snapshot } from '../shared/model.js';
import { api } from './api.js';
import { Management } from './Management.js';
import { Tree } from './Tree.js';
import { Viewer, type Signal } from './Viewer.js';
import './style.css';
const empty:Snapshot={projects:[],mounts:[],revision:0};
const labels:Record<string,string>={ready:'可访问','pending-build':'待构建','choose-entry':'待选择',online:'在线',offline:'离线',disabled:'已停用',scanning:'扫描中'};
function storedFavorites():string[]{try{return JSON.parse(localStorage.getItem('favorites')||'[]');}catch{return [];}}
export function App(){
  const standalone=location.pathname==='/preview';
  const [data,setData]=useState<Snapshot>(empty);const [entries,setEntries]=useState<Entry[]>([]);const [project,setProject]=useState('');const [view,setView]=useState('all');
  const [manage,setManage]=useState<'new'|'edit'>();const [error,setError]=useState('');const [selected,setSelected]=useState(new URLSearchParams(location.search).get('entry')||'');
  const [kind,setKind]=useState('');const [query,setQuery]=useState('');const [favorites,setFavorites]=useState<string[]>(storedFavorites);const [immersive,setImmersive]=useState(standalone);const [connection,setConnection]=useState('连接中');
  const [signal,setSignal]=useState<Signal>();const serial=useRef(0);const reloadVersion=useRef(0);const [treeRevision,setTreeRevision]=useState(0);
  async function reload(){const version=++reloadVersion.current;try{const [s,e]=await Promise.all([api<Snapshot>('/api/projects'),api<Entry[]>('/api/entries')]);if(version!==reloadVersion.current)return;setData(s);setEntries(e);setError('');}catch(e){setError((e as Error).message);}}
  useEffect(()=>{void reload();const source=new EventSource('/api/events');source.onopen=()=>setConnection('实时连接');source.onerror=()=>setConnection('连接中断，正在重连');
    for(const type of ['registry-changed','mount-state','entries-changed','resync'])source.addEventListener(type,event=>{void reload();if(type!=='mount-state'){setSignal({type,data:JSON.parse((event as MessageEvent).data),sequence:++serial.current});setTreeRevision(v=>v+1);}});
    return()=>source.close();
  },[]);
  function favorite(){if(!selected)return;setFavorites(old=>{const next=old.includes(selected)?old.filter(id=>id!==selected):[...old,selected];localStorage.setItem('favorites',JSON.stringify(next));return next;});}
  function navigate(mountId:string,relativePath:string){const e=entries.find(e=>e.mountId===mountId&&e.relativePath===relativePath);if(e)setSelected(e.id);else window.open(`/api/mounts/${mountId}/download?path=${encodeURIComponent(relativePath)}`,'_blank','noopener');}
  const visible=entries.filter(e=>(!project||e.projectId===project)&&(!kind||(kind==='other'?['text','data'].includes(e.kind):e.kind===kind))&&(view!=='tools'||e.kind==='tool')&&(view!=='favorites'||favorites.includes(e.id))&&`${e.title} ${e.relativePath} ${data.projects.find(p=>p.id===e.projectId)?.name}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>view==='recent'?b.updatedAt-a.updatedAt:Number(b.kind==='html')-Number(a.kind==='html')||a.title.localeCompare(b.title));
  const currentProject=data.projects.find(p=>p.id===project);const mounts=data.mounts.filter(m=>!project||m.projectId===project);
  return <div className={`shell ${immersive?'immersive':''}`}>
    <aside><h1>AgentDeck<span>LOCAL WORKBENCH</span></h1><button className="add-project" onClick={()=>setManage('new')}>＋ 添加项目</button><nav>{[['all','全部内容'],['recent','最近更新'],['tools','全部工具'],['favorites','收藏']].map(([id,name])=><button key={id} className={!project&&view===id?'active':''} onClick={()=>{setProject('');setView(id);setKind('');}}>{name}</button>)}</nav><p className="nav-label">我的项目</p>{data.projects.map(p=><button className={p.id===project?'active':''} key={p.id} onClick={()=>{setProject(p.id);setView('all');setKind('');}}>{p.name}<small>{data.mounts.filter(m=>m.projectId===p.id).length} 个目录</small></button>)}<div className="connection">● {connection}<small>本机运行 · 原文件只读</small></div></aside>
    <section className="catalog"><header><h2>{currentProject?.name||({all:'全部内容',recent:'最近更新',tools:'全部工具',favorites:'收藏'}[view])}</h2>{project&&<button aria-label="管理挂载" onClick={()=>setManage('edit')}>管理挂载</button>}</header><input aria-label="搜索" placeholder="搜索项目、名称或路径" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="类型筛选" value={kind} onChange={e=>setKind(e.target.value)}><option value="">全部类型</option><option value="html">HTML 报告 / 页面</option><option value="tool">工具</option><option value="markdown">Markdown</option><option value="other">其他 / 原文</option></select><div className="list-meta">{visible.length} 个入口 <button onClick={()=>void reload()}>刷新列表</button></div>
    {visible.map(e=><button className={`entry ${selected===e.id?'selected':''}`} key={e.id} onClick={()=>setSelected(e.id)}><span className={`badge ${e.kind}`}>{e.kind==='tool'?'工具':e.format.toUpperCase()||'HTML'}</span><strong>{e.title}</strong><small>{data.projects.find(p=>p.id===e.projectId)?.name} / {data.mounts.find(m=>m.id===e.mountId)?.label}</small><small>{e.relativePath||e.toolRoot||'根目录'}{favorites.includes(e.id)?' ★':''}</small>{e.status!=='ready'&&<small>{labels[e.status]}</small>}</button>)}
    {!visible.length&&<p className="muted">{data.projects.length?'没有符合条件的可读入口；可检查筛选、目录状态和工具构建结果。':'先添加项目并选择一个真实目录。'}</p>}
    <h3 className="nav-label">挂载与文件树</h3>{mounts.map(m=><details key={m.id}><summary>{m.label} <span className={m.status==='offline'?'offline':''}>· {labels[m.status]||m.status}</span></summary><small>{m.absolutePath}</small>{m.error&&<small role="alert">{m.error}</small>}<button onClick={()=>void api(`/api/mounts/${m.id}/rescan`,'POST').then(reload).catch(e=>setError(e.message))}>重新扫描</button>{m.enabled&&<Tree key={`${m.id}:${treeRevision}`} mount={m} open={p=>navigate(m.id,p)}/>}</details>)}{project&&<button className="output-note" onClick={()=>void navigator.clipboard.writeText(`本项目：${currentProject?.name}\n${mounts.map(m=>`${m.label}：${m.absolutePath}（${m.mode}）\n工具子目录：${m.toolDirectories.join('、')||'未指定'}`).join('\n')}\n请原地输出 HTML/Markdown；工具保留完整静态输出，使用相对资源与 hash 路由。来源写入正文。无需 manifest，不修改工作台源码。`).then(()=>setError('已复制当前项目输出约定。')).catch(e=>setError(e.message))}>复制输出路径说明</button>}</section>
    {selected?<Viewer key={selected} id={selected} signal={signal} favorite={favorites.includes(selected)} toggleFavorite={favorite} back={()=>{if(standalone)location.href='/';else {setSelected('');setImmersive(false);}}} immersive={immersive} setImmersive={setImmersive} navigate={navigate}/>:<section className="viewer"><div className="empty"><span className="eyebrow">YOUR FILES. IN PLACE.</span><h2>{data.projects.length?'选择一个报告，或启动工具。':'让每个项目拥有自己的工作台。'}</h2><p>直接阅读 HTML，运行纯前端工具。将已有目录加入项目，文件留在原位置。</p>{!data.projects.length&&<button className="primary" onClick={()=>setManage('new')}>添加第一个项目</button>}<p className="muted">支持多文件网页与完整构建输出。Markdown、CSV、JSON 可直接阅读。</p></div></section>}
    {error&&<div className="toast" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}{manage&&<Management snapshot={data} project={manage==='edit'?currentProject:undefined} close={()=>setManage(undefined)} saved={()=>void reload()}/>}
  </div>;
}
